Description: EC2 & ASG setup for counterstrike gaming server

Parameters:
  # inject in the latest AMI
  Linux2Ami:
    Type: String
  UserDataScript:
    Type: String
  instanceType:
    Type: String
    Default: t2.micro
  KeyName:
    Type: String
    Default: 'rhys-key-public'
  StudentName:
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'instanceType'
      SecurityGroups: []
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'Linux2Ami'
      NetworkInterfaces:
        - GroupSet:
            - !Ref InstanceSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId:
            Fn::ImportValue: !Sub '${StudentName}-pub-subnet-a-id'
  
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Sub '${StudentName}-vpc-id'
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:

      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'
        
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: '0.0.0.0/0'
        
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: '0.0.0.0/0'

# Exporting outputs to use in downstream stacks
Outputs:
  StackName:
    Value: !Ref AWS::StackName
